### PR TITLE
Convert to SocketPool

### PR DESCRIPTION
**Pull request by justmobilize**
For use with: https://github.com/adafruit/Adafruit_CircuitPython_ConnectionManager/pull/11

Converting from the old `adafruit_esp32spi/adafruit_esp32spi_socket.py` to `adafruit_esp32spi/adafruit_esp32spi_socketpool.py` to remove `set_interface` and work more like a built-in SocketPool.

This also allows one to use multiple ESP32SPI boards at the same time.

General example:
```py
import board
import busio
import digitalio
import os
import adafruit_requests
from adafruit_esp32spi.adafruit_esp32spi import ESP_SPIcontrol
import adafruit_esp32spi.adafruit_esp32spi_socketpool as socketpool

TEXT_URL = "http://wifitest.adafruit.com/testwifi/index.html"
wifi_ssid = os.getenv("CIRCUITPY_WIFI_SSID")
wifi_password = os.getenv("CIRCUITPY_WIFI_PASSWORD")

esp32_cs = digitalio.DigitalInOut(board.D13)
esp32_ready = digitalio.DigitalInOut(board.D11)
esp32_reset = digitalio.DigitalInOut(board.D12)
spi_bus = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
radio = ESP_SPIcontrol(spi_bus, esp32_cs, esp32_ready, esp32_reset)
radio.connect_AP(wifi_ssid, wifi_password)
pool = socketpool.SocketPool(radio)
requests = adafruit_requests.Session(pool)
print(requests.get(TEXT_URL).text)
```

or with the new `ConnectionManager`
```py
import board
import busio
import digitalio
import os
import adafruit_connection_manager
import adafruit_requests
from adafruit_esp32spi.adafruit_esp32spi import ESP_SPIcontrol
from adafruit_esp32spi import adafruit_esp32spi_socketpool

TEXT_URL = "http://wifitest.adafruit.com/testwifi/index.html"
wifi_ssid = os.getenv("CIRCUITPY_WIFI_SSID")
wifi_password = os.getenv("CIRCUITPY_WIFI_PASSWORD")

esp32_cs = digitalio.DigitalInOut(board.D13)
esp32_ready = digitalio.DigitalInOut(board.D11)
esp32_reset = digitalio.DigitalInOut(board.D12)
spi_bus = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
radio = ESP_SPIcontrol(spi_bus, esp32_cs, esp32_ready, esp32_reset)
radio.connect_AP(wifi_ssid, wifi_password)
pool = adafruit_connection_manager.get_radio_socketpool(radio)
assert isinstance(pool, adafruit_esp32spi_socketpool.SocketPool)
requests = adafruit_requests.Session(pool)
print(requests.get(TEXT_URL).text)
```

### CODE REVIEW

**Comment by anecdata** [comment]
Looks good!

Config:
`Adafruit CircuitPython 9.0.0-4-g5dadc13cac on 2024-03-21; FeatherS3 with ESP32S3`
Airlift FeatherWing
adafruit_esp32spi PR 198 (this PR)
adafruit_connection_manager PR 11 (Use new SocketPool for ESP32SPI and WIZNET5K)
(all other libraries: latest release)

<details>
<summary>code...</summary>

```py
import time
import os
import traceback
import board
import busio
import digitalio
import os
import adafruit_connection_manager
import adafruit_requests
from adafruit_esp32spi.adafruit_esp32spi import ESP_SPIcontrol

URLS = ("http://wifitest.adafruit.com/testwifi/index.html", "https://httpbin.org/get")

def get_requests(radio):
    # this allows creating multiple requests sessions for multiple devices
    pool = adafruit_connection_manager.get_radio_socketpool(radio)
    ssl_context = adafruit_connection_manager.get_radio_ssl_context(radio)
    requests = adafruit_requests.Session(pool, ssl_context)
    return requests

def connect_esp(radio):
    while not radio.is_connected:
        try:
            radio.connect_AP(os.getenv("WIFI_SSID"), os.getenv("WIFI_PASSWORD"))
        except Exception as ex:
            traceback.print_exception(ex, ex, ex.__traceback__)
    ipv4_str = radio.pretty_ip(radio.ip_address)
    return ipv4_str

spi = board.SPI()
esp32_cs = digitalio.DigitalInOut(board.A0)
esp32_reset = digitalio.DigitalInOut(board.A1)
esp32_ready = digitalio.DigitalInOut(board.A2)
radio = ESP_SPIcontrol(spi, esp32_cs, esp32_ready, esp32_reset, debug=False)
requests_esp = get_requests(radio)
while True:
    print(f'{"="*25}')
    for url in URLS:
        print(f'{"-"*25}')
        print(f"Fetching from {url} via ESP32SPI {connect_esp(radio)} ", end="")
        with requests_esp.get(url) as resp:
            print(f'{resp.status_code} {resp.reason.decode()}')
        time.sleep(5)
```
</details>

**Comment by dhalbert** [comment]
This kind of bypasses https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/main/adafruit_esp32spi/adafruit_esp32spi_wifimanager.py. Do you see that as being supplanted by ConnectionManager eventually? It does have functionality CM does not.

I was interested in replacing the `secrets` arg in wifimanager with something that looked up settings in `settings.toml`, if `secrets`, and/or replacing `secrets` with separate `ssid` and `password` args. But I haven't looked in great detail at this: it was something I noticed while trying to get rid of uses of `secrets.py` in Learn Guides.

**Comment by anecdata** [comment]
To me so far, Connection Manager is all about sockets, and it's shaping up to be very versatile for single- and multiple-network configurations. I seem to recall a discussion about whether it should take on additional features like wifi connection, but don't remember the conclusion. I couldn't find anything in In The Weeds from this year. I have some concern about CM getting too big with disparate features.

**Comment by justmobilize** [comment]
@dhalbert I would love to take out the rest of secrets. If you help me come up with the right path, I take it and run

**Comment by dhalbert** [comment]
@anecdata Thanks for that perspective.
@justmobilize Then I would just do what I said above: modernize wifi manager, and finish cleaning up the remaining guides. Not urgent, but I will look at this relatively soon. I agree about keeping CM small for now.

**Comment by justmobilize** [comment]
@dhalbert wifi manager is already using the ConnectionManager ([here](https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/main/adafruit_esp32spi/adafruit_esp32spi_wifimanager.py#L69)), so would these changes should all automatically apply

**Review by anecdata — COMMENTED** [review]
Re-tested with https://github.com/adafruit/Adafruit_CircuitPython_ConnectionManager/pull/11#pullrequestreview-2027291082. Good to go pending any others with code review

**Comment by dhalbert** [comment]
Looks good, but is this an incompatible change? If so, then we need to update Guide code right away after merging this.

**Comment by justmobilize** [comment]
Only if they aren't using ConnectionManager. Here's the only guide we need to update: https://github.com/search?q=repo%3Aadafruit%2FAdafruit_Learning_System_Guides+adafruit_esp32spi_socket&type=code

**Comment by dhalbert** [comment]
OK, let's merge this, and then if you can make a PR to the Learn Guide repo, that would be great.

**Review by dhalbert — APPROVED** [review]
Thanks! Updating ConnectionManager at same time.

**Pull request merged**
