### PR TITLE
Optional HTTP response on error

### PR DESCRIPTION
**Pull request by tekktrik**
This provides the ability to return a given HTTP response whenever an `Exception` is hit executing user code.  This allows the WSGI server to notify if a failure occurred and continue running without completely crashing.  It catches `Exception` in order to catch almost all errors since the intention is to try to keep the server alive.  If nothing is given, previous behavior is retain, which may be desirable?

### CODE REVIEW

**Review by dhalbert — COMMENTED** [review]
IThanks! I am looking at `adafruit_requests` and this library and native `wifi` support on ESP32-S2, and trying to regularize the use of exceptions between the three. SO will be reviewing this, but not immediately.

**Comment by tekktrik** [comment]
Sounds good!  I love the WSGI libraries so I've just playing around there lately.  Happy to changes as needed.

**Comment by tekktrik** [comment]
Converting to a draft so it doesn't accidentally get merged in the meantime

**Comment by tekktrik** [comment]
@dhalbert just checking in on this since it's been a few weeks, happy to keep this hibernating for now

**Comment by tekktrik** [comment]
@dhalbert is this good to go or are you still working on the other libraries?  I can change this to a draft in the meantime if so.

**Comment by tekktrik** [comment]
Just checking in on this @dhalbert to see if it's still relevant

**Comment by tekktrik** [comment]
Based on previous discussions on how libraries like this might change, I'm closing for now.  I'll open it up again later if it makes sense.

**Pull request closed without merging**
