### PR TITLE
fix .server_state() attribute name

### PR DESCRIPTION
**Pull request by anecdata**
`AttributeError: 'ESP_SPIcontrol' object has no attribute 'get_server_state'`

### CODE REVIEW

**Comment by anecdata** [comment]
I'm not actively working on WSGIServer, but noticed this when looking at it to make a simple TCP socket server example.

**Comment by jposada202020** [comment]
@anecdata :) could you guide me in how to test this, I have the hardware2 but my `network` knowledge is not au-pair. If you have some basic test code I could replicate. Let me know thanks

**Comment by anecdata** [comment]
@jposada202020  There is an example, I've only run it once:
https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/tree/master/examples/server
Should run on any ESP32SPI combination (PyPortal, M4+Airlift, etc.)

Once it's running, any web client can load the web page, the server will print out its IP address, and the port is 80..

If you want, here or on Discord, I can set it up in parallel with you and step through it.

**Comment by anecdata** [comment]
Oh yeah, and in line 232 of the example, you have to turn debug on to exercise the PR change:
`wsgiServer = server.WSGIServer(80, application=web_app, debug=True)`

**Comment by jposada202020** [comment]
This was tested, and it works as described
```py
Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Adafruit PyPortal Titano with samd51j20
>>> import esp32spi_wsgiserver
ESP32 SPI simple web server test!


open this IP in your browser:  192.168.2.68
Server available at 192.168.2.68:80
Sever status:  1
```
We have a long discussion over the #help-with-circuitpython-channel during our testing, if anyone is interested in this
@brentru coud you take a look. Thanks

**Comment by JayToltTech** [comment]
FYI, just hit this myself, looking into the example code of how to implement a simple socket server with Featherwing Airlift...

**Review by FoamyGuy — APPROVED** [review]
Looks good to me as well.

Tested successfully on:
```
Adafruit CircuitPython 7.1.0-beta.0 on 2021-11-12; Adafruit PyPortal with samd51j20
Board ID:pyportal
```

**Pull request merged**
