### PR TITLE
Fixed MAC reverse byte order issue.

### PR DESCRIPTION
**Pull request by mytechnotalent**
Fixed MAC reverse byte order issue as it was originally reporting the MAC address in reverse byte order.

### CODE REVIEW

**Comment by ladyada** [comment]
how about ya look at fixing it the readmac() code instead of post-fixing? :) thats better!

**Comment by mytechnotalent** [comment]
Sorry I was just trying to be helpful.  I will have to find what library that exists.  I will search now.

**Comment by ladyada** [comment]
you're being helpful, but you could be SUPER helpful and solve this for everyone :D

**Comment by mytechnotalent** [comment]
Indeed LadyAda!  I shall take up the task :)

**Comment by ladyada** [comment]
ganbatte! you can do it!!!

**Comment by mytechnotalent** [comment]
LOL yes searching the libraries now to find where readmac() lives should have it shortly.

**Comment by mytechnotalent** [comment]
Closing - per @ladyada request will update library rather than example code.  New pull will be created shortly.  Standby...

**Pull request closed without merging**
