### PR TITLE
Use secrets.py for ssid and password.

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Comment by ladyada** [comment]
we'd have to update the guide as well

**Comment by tannewt** [comment]
Yup, there are big warnings to manually replace them but it felt weird after setting up the secrets file. I'm curious why it is that way.

**Comment by ladyada** [comment]
used to come before the secrets file, perhaps it got rearranged - @brentru any feelings either way?

**Comment by dhalbert** [comment]
There was a warning below the example; I put another warning above, after helping someone on discord (and being confused myself).

**Comment by brentru** [comment]
@ladyada  I'm OK with this update, it'll reduce confusion.

The Internet Connect! page lists the *`secrets.py` setup* step (https://learn.adafruit.com/adafruit-pyportal/internet-connect#whats-a-secrets-file-17-1) step before the *Connect to WiFi* step.

Once merged and released, I'll change text on the *Connect to WiFi* (https://learn.adafruit.com/adafruit-pyportal/internet-connect#connect-to-wifi-17-4) step to reflect the updated code.

**Comment by ladyada** [comment]
turns out that nobody updated the guide. i did it now.

**Pull request merged**
