### PR TITLE
Change _pin arguments to _dio

### PR DESCRIPTION
**Pull request by tekktrik**
Addresses Issue #121 by changing relevant argument names from `*_pin` to `*_dio`.  I chose this instead of just using `*` argument names so it would be explicitly clear it should be a `DigitalInOut` instance passed as the argument, and also because I know there is a `reset` parameter so that argument wouldn't be confused for a boolean argument or something like that.

### CODE REVIEW

**Comment by ladyada** [comment]
can you check if any examples/code use the old naming?

**Comment by tekktrik** [comment]
Will do!

**Comment by tekktrik** [comment]
It looks like all the pin arguments in the examples in the repo are named `esp32_*` like `esp32_reset`.  Should I check the Learn guides as well, or would those reference the examples?

**Comment by ladyada** [comment]
yah check the learn system, its kinda risky to change arg names :/ lots of code can break

**Comment by tekktrik** [comment]
A quick search for ESP32 products and reading the guides shows that the examples (no references other than code examples) always use the same variable naming scheme of `esp32_*` and the arguments are never done as keywords, only positional.

**Comment by tekktrik** [comment]
Is this all good?  Happy to do anything needed if this is a viable PR still!

**Comment by ladyada** [comment]
@jerryneedell any thoughts? just cause you deal with this stuff more recently than i!

**Comment by jerryneedell** [comment]
No concerns from me. Than you for asking!

**Review by anecdata — COMMENTED** [review]
I've only seen instantiation positional, typically with variables assigned from the `DigitalInOut`s:
`esp = adafruit_esp32spi.ESP_SPIcontrol(spi, esp32_cs, esp32_ready, esp32_reset)`
Tested PR code on PyPortal, change is transparent.

**Comment by tekktrik** [comment]
Any decision on this? Happy to change the names to something else as well if those aren't clear.

**Review by FoamyGuy — APPROVED** [review]
Looks good to me, I agree in thinking that `*_dio` makes it more clear what is expected to be passed for those arguments.

I tested these changes successfully with the requests simpletest on a PyPortal 7.2.0-alpha.1.

I also used `git grep "cs_pin="` and similar to search for usages of these argument names in the Learning System repo and did not find any code using those names to instantiate this library.  

However there are a few other libraries with similarly named `*_pin` arguments that are actually expecting DigitalIO objects like this one. I'll open issues on those repo's I would assume we want to be consistent about the argument naming across repos.

**Comment by tekktrik** [comment]
Sounds good!  I'd be happy to look into how easily they can get a PR without breaking code!

**Pull request merged**
